# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "pagenvm"
  config.vm.hostname = "pagen"
  # config.vm.network "private_network", ip: "192.168.66.99"
  config.vm.synced_folder "./sync", "/home/vagrant/sync"

  config.vm.provider "virtualbox" do |vb, override|
    override.vm.box_url = "//wanjiana26/share/pagenvm.box"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
end
